spring:
  application:
    name: flex-training-backend
  cloud:
    aws:
      region:
        static: ap-northeast-2
  config:
    import:
  datasource:
    url: jdbc:h2:mem:testdb
    username: training
    password:
  h2:
    console:
      enabled: true


server:
  tomcat:
    mbeanregistry:
      enabled: true

#### Actuator 공통 설정
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - loggers
  endpoint:
    health:
      probes:
        enabled: true

#### secrets
---

spring:
  config:
    activate:
      on-profile: local-dev

# local에서 server port 충돌을 피하기 위한 설정. gateway에 붙어야하면 이것을 기록해두는게 좋습니다
server:
  port: 12345

management:
  endpoints:
    web:
      exposure:
        include: '*'
