name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: lint and sanity test
      id: lint-and-sanity-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: lint and sanity test
        setup-command: ''
        command: "./gradlew check"
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LINT-AND-SANITY-TEST_RESULTS: "${{steps.lint-and-sanity-test.outputs.result}}"
      with:
        runners: lint-and-sanity-test
